####Este aqui Ã© a primeira parte do curso, realizando apenas build da imagem |
##Criando e configurando o repositorio


name: CDGitops

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push image to Dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/gitopsfc
        #repository: carlosadrianosouza/gitopsfc
        #username: "carlosadrianosouza"
        #password: "dckr_pat_tG0o0gljJgGk7HC15cb-_01-rio"        
        tags: ${{ github.sha }}, latest

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with: 
        kustomize-version: "3.6.1"
    
    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd k8s
        kustomize edit set image goserver=$DOCKER_USERNAME/gitopsfc:$GITHUB_SHA
    
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker version"
    
    - name: Push-v-1521
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}        
        repository: carlosadrianosouza/gitopsfc